### ISSUE TITLE
Network adapter not always ENS33

### ISSUE THREAD

**Issue by PolygonHJ** [fanthore/F4-220#3]
I found your guide helpful to get me on the right track - I used Ubuntu server rather than OMV but found my device could not connect to my network. This was because my network interface was `enp2s0`.

A simple solution to finding the networking interface for me was to:
- Boot the USB bootable from another machine (with a display)
- Add `5 * * * * ip a > /home/ip` to your crontab
- Boot the TNAS with the USB
- Leave running for 10 minutes
- Shutdown the TNAS
- Use the bootable on the machine with a display
- Copy the file to a new location (so it doesn't get overwritten by cron)
- Read the file to find the interface

The follow standard process to add the interface to the network configuration.

**Comment by fanthore** [comment]
Sorry for the late reply, I rarely use my personal github account these days as I mostly use my work account. 

You remarks make perfect sense. Your procedure can also be used to debug quickly .

My debug procedure is a little more complex as I have to 

- open the enclosure and unplug the drive
- transform it to .iso format and save it on a computer
- start it in a VM using VirtualBox 
- make changes
- then save to iso and copy back to USB 
- mount back to device

Thanks for the comment!
