### ISSUE TITLE
about Terramaster New product review and test

### ISSUE THREAD

**Issue by speeedturtle** [fanthore/F4-220#4]
TerraMaster pre-released a new NAS, and looking for professionals to test it.

Are you interested?

Drop me a msg.

**Comment by cinzas** [comment]
@speeedturtle what are you looking for in particular ?

I have a F4-220 running with 4 3TB SATA disk, and one SSD disk plugged in internally in the USB2.0 socket. 
I have added 2GB of RAM and using currently the OMV.

Some tweaks to have LED's and FAN's running as expected :)

**Comment by speeedturtle** [comment]
> @speeedturtle what are you looking for in particular ?
> 
> I have a F4-220 running with 4 3TB SATA disk, and one SSD disk plugged in internally in the USB2.0 socket. I have added 2GB of RAM and using currently the OMV.
> 
> Some tweaks to have LED's and FAN's running as expected :)

Cinzas, are you willing to write a review post or upload review videos to YouTube for Terramaster?

How can I PM you?
